export const TEAM_NAMES_ES = {
  'Afghanistan': 'Afganistán',
  'Albania': 'Albania',
  'Algeria': 'Argelia',
  'Andorra': 'Andorra',
  'Angola': 'Angola',
  'Argentina': 'Argentina',
  'Armenia': 'Armenia',
  'Australia': 'Australia',
  'Austria': 'Austria',
  'Azerbaijan': 'Azerbaiyán',
  'Bahamas': 'Bahamas',
  'Bahrain': 'Baréin',
  'Bangladesh': 'Bangladesh',
  'Belarus': 'Bielorrusia',
  'Belgium': 'Bélgica',
  'Belize': 'Belice',
  'Benin': 'Benín',
  'Bolivia': 'Bolivia',
  'Bosnia and Herzegovina': 'Bosnia y Herzegovina',
  'Botswana': 'Botsuana',
  'Brazil': 'Brasil',
  'Brunei': 'Brunéi',
  'Bulgaria': 'Bulgaria',
  'Burkina Faso': 'Burkina Faso',
  'Burundi': 'Burundi',
  'Cambodia': 'Camboya',
  'Cameroon': 'Camerún',
  'Canada': 'Canadá',
  'Cape Verde': 'Cabo Verde',
  'Central African Republic': 'República Centroafricana',
  'Chad': 'Chad',
  'Chile': 'Chile',
  'China': 'China',
  'Colombia': 'Colombia',
  'Comoros': 'Comoras',
  'Congo': 'Congo',
  'Costa Rica': 'Costa Rica',
  'Croatia': 'Croacia',
  'Cuba': 'Cuba',
  'Cyprus': 'Chipre',
  'Czech Republic': 'República Checa',
  'Czechia': 'República Checa',
  'Denmark': 'Dinamarca',
  'Djibouti': 'Yibuti',
  'Dominica': 'Dominica',
  'Dominican Republic': 'República Dominicana',
  'Ecuador': 'Ecuador',
  'Egypt': 'Egipto',
  'El Salvador': 'El Salvador',
  'England': 'Inglaterra',
  'Equatorial Guinea': 'Guinea Ecuatorial',
  'Eritrea': 'Eritrea',
  'Estonia': 'Estonia',
  'Ethiopia': 'Etiopía',
  'Fiji': 'Fiyi',
  'Finland': 'Finlandia',
  'France': 'Francia',
  'Gabon': 'Gabón',
  'Gambia': 'Gambia',
  'Georgia': 'Georgia',
  'Germany': 'Alemania',
  'Ghana': 'Ghana',
  'Gibraltar': 'Gibraltar',
  'Greece': 'Grecia',
  'Grenada': 'Granada',
  'Guatemala': 'Guatemala',
  'Guinea': 'Guinea',
  'Guinea-Bissau': 'Guinea-Bisáu',
  'Guyana': 'Guyana',
  'Haiti': 'Haití',
  'Honduras': 'Honduras',
  'Hong Kong': 'Hong Kong',
  'Hungary': 'Hungría',
  'Iceland': 'Islandia',
  'India': 'India',
  'Indonesia': 'Indonesia',
  'Iran': 'Irán',
  'Iraq': 'Irak',
  'Ireland': 'Irlanda',
  'Israel': 'Israel',
  'Italy': 'Italia',
  'Ivory Coast': 'Costa de Marfil',
  'Jamaica': 'Jamaica',
  'Japan': 'Japón',
  'Jordan': 'Jordania',
  'Kazakhstan': 'Kazajistán',
  'Kenya': 'Kenia',
  'Kosovo': 'Kosovo',
  'Kuwait': 'Kuwait',
  'Kyrgyzstan': 'Kirguistán',
  'Laos': 'Laos',
  'Latvia': 'Letonia',
  'Lebanon': 'Líbano',
  'Lesotho': 'Lesoto',
  'Liberia': 'Liberia',
  'Libya': 'Libia',
  'Liechtenstein': 'Liechtenstein',
  'Lithuania': 'Lituania',
  'Luxembourg': 'Luxemburgo',
  'Macao': 'Macao',
  'Macedonia': 'Macedonia',
  'Madagascar': 'Madagascar',
  'Malawi': 'Malaui',
  'Malaysia': 'Malasia',
  'Maldives': 'Maldivas',
  'Mali': 'Mali',
  'Malta': 'Malta',
  'Mauritania': 'Mauritania',
  'Mauritius': 'Mauricio',
  'Mexico': 'México',
  'Moldova': 'Moldavia',
  'Monaco': 'Mónaco',
  'Mongolia': 'Mongolia',
  'Montenegro': 'Montenegro',
  'Morocco': 'Marruecos',
  'Mozambique': 'Mozambique',
  'Myanmar': 'Myanmar',
  'Namibia': 'Namibia',
  'Nepal': 'Nepal',
  'Netherlands': 'Países Bajos',
  'New Zealand': 'Nueva Zelanda',
  'Nicaragua': 'Nicaragua',
  'Niger': 'Níger',
  'Nigeria': 'Nigeria',
  'North Korea': 'Corea del Norte',
  'Northern Ireland': 'Irlanda del Norte',
  'Norway': 'Noruega',
  'Oman': 'Omán',
  'Pakistan': 'Paquistán',
  'Palestine': 'Palestina',
  'Panama': 'Panamá',
  'Papua New Guinea': 'Papúa Nueva Guinea',
  'Paraguay': 'Paraguay',
  'Peru': 'Perú',
  'Philippines': 'Filipinas',
  'Poland': 'Polonia',
  'Portugal': 'Portugal',
  'Qatar': 'Catar',
  'Romania': 'Rumania',
  'Russia': 'Rusia',
  'Rwanda': 'Ruanda',
  'Saint Kitts and Nevis': 'San Cristóbal y Nieves',
  'Saint Lucia': 'Santa Lucía',
  'Saint Vincent and the Grenadines': 'San Vicente y las Granadinas',
  'Samoa': 'Samoa',
  'San Marino': 'San Marino',
  'Sao Tome and Principe': 'Santo Tomé y Príncipe',
  'Saudi Arabia': 'Arabia Saudita',
  'Scotland': 'Escocia',
  'Senegal': 'Senegal',
  'Serbia': 'Serbia',
  'Seychelles': 'Seychelles',
  'Sierra Leone': 'Sierra Leona',
  'Singapore': 'Singapur',
  'Slovakia': 'Eslovaquia',
  'Slovenia': 'Eslovenia',
  'Solomon Islands': 'Islas Salomón',
  'Somalia': 'Somalia',
  'South Africa': 'Sudáfrica',
  'South Korea': 'Corea del Sur',
  'South Sudan': 'Sudán del Sur',
  'Spain': 'España',
  'Sri Lanka': 'Sri Lanka',
  'Sudan': 'Sudán',
  'Suriname': 'Surinam',
  'Swaziland': 'Esuatini',
  'Sweden': 'Suecia',
  'Switzerland': 'Suiza',
  'Syria': 'Siria',
  'Taiwan': 'Taiwán',
  'Tajikistan': 'Tayikistán',
  'Tanzania': 'Tanzania',
  'Thailand': 'Tailandia',
  'Timor-Leste': 'Timor Oriental',
  'Togo': 'Togo',
  'Tonga': 'Tonga',
  'Trinidad and Tobago': 'Trinidad y Tobago',
  'Tunisia': 'Túnez',
  'Turkey': 'Turquía',
  'Turkmenistan': 'Turkmenistán',
  'Turks and Caicos Islands': 'Islas Turcas y Caicos',
  'Uganda': 'Uganda',
  'Ukraine': 'Ucrania',
  'United Arab Emirates': 'Emiratos Árabes Unidos',
  'United States': 'Estados Unidos',
  'Uruguay': 'Uruguay',
  'Uzbekistan': 'Uzbekistán',
  'Vanuatu': 'Vanuatu',
  'Venezuela': 'Venezuela',
  'Vietnam': 'Vietnam',
  'Wales': 'Gales',
  'Yemen': 'Yemen',
  'Zambia': 'Zambia',
  'Zimbabwe': 'Zimbabue',
};

export function getTeamNameES(teamName) {
  return TEAM_NAMES_ES[teamName] || teamName;
}
